### ISSUE TITLE
Does not work with winform app

### ISSUE THREAD

**Issue by pagelinsan** [AshV/Firebase.Net#1] opened 2017-12-16 22:45 UTC
Hello, 
i copy your files to another winform project .Net4.6. When i click button to send data, it hangs at line 
 ACCESS_TOKEN = GetAccessTokenFromJSONKeyAsync(jsonKeyFilePath, AuthHelper.scopes).Result;

If i change project to console project , it worka perfectly. 
Do you have any idea?

Thanks you,
Dang

**Comment by AshV** [comment] 2017-12-21 17:54
Hey @pagelinsan  I have reproduced the issue it's going to infinite await in GetAccessTokenFromJSONKeyAsync(). I think it's because STAThread used in Windows Forms App.
Could you please try the same in WPF application?

**Comment by pagelinsan** [comment] 2017-12-23 21:59
Hi, 
i found the problem is deadlock. After changing some await and async, it works perfectly
ACCESS_TOKEN = await GetAccessTokenFromJSONKeyAsync(jsonKeyFilePath, AuthHelper.scopes);

Thanks you.

**Comment by AshV** [comment] 2017-12-25 17:16
That's good to know, thanks for finding and resolving it.

**Closed as completed by AshV** 2017-12-25 17:16 UTC
